server:
  port: 8001

spring:
  application:
    name: cloud-login-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    
eureka:
  instance:
    prefer-ip-address: true
    instance-id: login8001
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jzy.entity
  configuration:
    map-underscore-to-camel-case: true
